#ifndef __GLOBALDEFS_H
#define __GLOBALDEFS_H

#define PLAYER_NOMOVEMENT 1
#define PLAYER_MOVEMENT 2
#define PLAYER_MOVING 3
#define AI_DISPLAY 4
#define PLAYERMOVE 100
#define AIMOVE 100
#define JOBAMOUNT 100
#define MAGICAMOUNT 100
#define PLAYERITEMS 100
#define STATUSEFFECTSAMOUNT 100
#define WEAPONSAMOUNT 100
#define THIEFINGAMOUNT 100
#define THIEFINGITEMAMOUNT 100
#define CHARACTERSTRINGLENGTH 200
#define SHIELDAMOUNT 100
#define CHARACTERAMOUNT 100
#define MAGICAMOUNT 100
#define ARMORAMOUNT 100
#define ALLDEFENSEITEMS 100
#define CLASSAMOUNT 100

#endif

